[tools]
"core:dotnet" = "10.0.202"
python = "3.13"
uv = "latest"
"pipx:gitingest" = { version = "latest" }
"pipx:pre-commit" = { version = "latest" }

[settings]
python.uv_venv_auto = true

[tasks.build]
alias = "build"
description = "Build the solution."
run = ["dotnet build Night.slnx"]

[tasks.game]
alias = "game"
description = "Run the sample game."
run = ["dotnet run --project src/SampleGame/SampleGame.csproj"]

[tasks.clean]
alias = "clean"
description = "Clean bin and obj directories."
run = ["dotnet clean Night.slnx"]

[tasks.sdl]
description = "Update SDL bindings and sync SDL libs."
run = [
  "git submodule update --remote lib/SDL3-CS",
  "python scripts/sync_sdl3.py",
]

[tasks.tools]
description = "Update tools."
run = [
  "git submodule update --remote lib/SDL3-CS",
  "python scripts/update_tools.py",
]

[tasks.update-api-doc]
description = "Update API docs."
run = ["python scripts/update_api_doc.py"]

[tasks.prepare]
alias = "prepare"
description = "Prepare everything before a commit."
run = [
  "dotnet clean Night.slnx",
  "dotnet format --verbosity diagnostic Night.slnx",
  "dotnet build Night.slnx",
  "dotnet test",
  "dotnet docfx docs/docfx.json",
  "python scripts/update_api_doc.py",
]

[tasks.docs]
alias = "docs"
description = "Generate docs."
run = ["dotnet docfx docs/docfx.json"]

[tasks.format]
alias = "format"
description = "Format files."
run = ["dotnet format --verbosity verbose Night.slnx"]
