[tools]
dotnet = "9"
python = "3.13"
"pipx:gitingest" = { version = "latest" }
"pipx:pre-commit" = { version = "latest" }

[settings]
python.uv_venv_auto = true

[tasks.digest]
description = "Run gitingest on current directory."
run = [
  "gitingest -o docs/digest.txt -e *.toml,*.txt,.roo/*,.cursor/*,build/*,.devenv/*,.direnv/*,docs/digest.txt,docs/archive/*,*.lock,bin/*,obj/* .",
  "sed -i'' -e :a -e '/^\\n*$/{$d;N;ba' -e '}' docs/digest.txt && echo >> docs/digest.txt",
  "sed -i'' '$ { /^$/ d; }' docs/digest.txt"
]
