name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive' # Ensure submodules like SDL are checked out

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | # Specify SDK versions if particular ones are needed, or remove for latest
          9.0.x

    - name: Check Formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic Night.sln

    - name: Restore dependencies
      run: dotnet restore Night.sln

    - name: Build Solution
      run: dotnet build Night.sln --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test tests/Night.Tests/Night.Tests.csproj --no-build --configuration Release
