name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Check Formatting
      run: dotnet format --verify-no-changes --verbosity diagnostic Night.slnx

    - name: Restore dependencies
      run: dotnet restore Night.slnx

    - name: Build Solution
      run: dotnet build Night.slnx --configuration Release --no-restore

    - name: Run Tests
      env:
        SDL_VIDEODRIVER: dummy
      run: dotnet test tests/NightTest.csproj --no-build --configuration Release --filter "TestType=Automated"
